# Generated by Django 3.0.7 on 2020-06-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='medico',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medico.Especialidade'),
            preserve_default=False,
        ),
    ]
