# Generated by Django 3.0.7 on 2020-06-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('especialidade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medico.Especialidade')),
            ],
        ),
    ]
